eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka

spring:
  application:
    name: pg-gw
  server:
    port: 8080
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: users-status
          uri: lb://pg-users
          predicates:
            - Path=/users/status
            - Method=GET
          filters:
            - RemoveRequestHeader=Cookie

